version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mysql:
    image: taylor840326/mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    environment:
      - MYSQL_ROOT_PASSWORD=111111
    command:
      - --server_id=1
      - --port=3306
      - --character_set_server=utf8
      - --collation_server=utf8_general_ci
      - --innodb_log_files_in_group=4
      - --innodb_log_file_size=1G
      - --innodb_buffer_pool_size=1G
      - --innodb_log_buffer_size=16777216
      - --max_length_for_sort_data=8192
      - --innodb_data_file_path=ibdata1:1G:autoextend
      - --innodb_file_per_table=ON
      - --innodb_file_format=Barracuda
      - --innodb_file_format_max=Barracuda
      - --innodb_undo_tablespaces=1
      - --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - --binlog_format=ROW
      - --log_bin=archlogs
    restart: on-failure
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - "3000:3000"
    restart: on-failure

